{% set name = "roms-lite" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/roms-lite

requirements:
  build:
    - python
    - gcc
    - libgfortran
    - mpich2
    - libnetcdf
    - netcdf-fortran

  run:
    - python
    - libnetcdf
    - netcdf-fortran
    - libgfortran
    - mpich2

build:
  number: 0
